package exception;

public class Test16 {
	public static void main(String[] args)
	{
		try
		{
			
		}
		catch (ArithmeticException e)
		{
			
		}
		finally
		{
			try 
			{
				
			}
			catch(Exception e1)
			{
				
			}
		}
	}

}
