package exception;

public class Test15 {
	public static void main (String args[])
	{
		try
		{
			
		}
		catch(ArithmeticException e)
		{
			try
			{
				
			}
			catch(Exception e1)
			{
				
			}
			
		}
	}

}
